backend:
  name: github
  repo: EmanonEnt/asia
  branch: main
  base_url: https://sensational-kangaroo-9944d9.netlify.app
  auth_endpoint: /api/v1/auth
publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img
