backend:
  name: github
  repo: EmanonEnt/asia
  branch: main
  site_domain: emanonent.github.io

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "index.md"
        fields:  # 这里必须严格缩进，且用冒号格式
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "body", widget: "markdown"}
